<?php
// $Id$

/**
 * @file
 * Defines standard simple field types.
 */

/**
 * Implementation of hook_help().
 */
function field_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Defines standard simple field types.');
  }
}

/**
 * Implementation of hook_field_info().
 */
function field_field_info() {
  return array(
    'field_shorttext' => array('label' => 'Short Text'),
    'field_longtext' => array('label' => 'Long Text'),
    'field_integer' => array('label' => 'Integer'),
    'field_decimal' => array('label' => 'Decimal')
  );
}

/**
 * Implementation of hook_field_settings().
 */
function field_field_settings($op, $field, $scope) {
  switch ($op) {
    case 'form':
      $form = array();
      switch ($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          switch ($scope) {
            case 'instance':
              $form['rows'] = array(
                '#type' => 'textfield',
                '#title' => t('Rows'),
                '#default_value' => $field['rows'] ? $field['rows'] : 1,
                '#required' => TRUE,
              );
              break;

            case 'global':
              $options = array(0 => t('Plain text'), 1 => t('Filtered text (user selects input format)'));
              $form['text_processing'] = array(
                '#type' => 'radios',
                '#title' => t('Text processing'),
                '#default_value' => $field['text_processing'] ? $field['text_processing'] : 0,
                '#options' => $options,
              );
              break;
          }
        break;
        case 'field_integer':
        case 'field_decimal':
          switch ($scope) {
            case 'global':
              $form['min'] = array(
                '#type' => 'textfield',
                '#title' => t('Minimum'),
                '#default_value' => $field['min'] ? $field['min'] : '',
              );
              $form['max'] = array(
                '#type' => 'textfield',
                '#title' => t('Maximum'),
                '#default_value' => $field['min'] ? $field['min'] : '',
              );
              break;
          }
          break;
      }
      return $form;
    
    case 'validate':
      switch ($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          switch ($scope) {
            case 'instance':
              if (!is_numeric($field['rows']) || intval($field['rows']) != $field['rows'] || $field['rows'] <= 0) {
                form_set_error('rows', t('"Rows" must be a positive integer.'));
              }
              break;
          }
        break;
        case 'field_integer':
        case 'field_decimal':
          switch ($scope) {
            case 'global':
              if ($field['min'] && !is_numeric($field['min'])) {
                form_set_error('rows', t('"Minimum" must be a number.'));
              }
              if ($field['max'] && !is_numeric($field['max'])) {
                form_set_error('rows', t('"Maximum" must be a number.'));
              }
              break;
          }
          break;
      }
      break;

    case 'save':
      switch ($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          switch ($scope) {
            case 'instance':
              return array('rows');
            case 'global':
              return array('text_processing');
          }
          break;
        case 'field_integer':
        case 'field_decimal':
          switch ($scope) {
            case 'instance':
              return array();
            case 'global':
              return array('min', 'max');
          }
          break;
      }
    break;
  }
}

/**
 * Implementation of hook_field().
 */
function field_field($op, $node, $field, $a2, $a3, $a4) {
  switch ($op) {
    case 'load':
      switch($field['type']) {
        case 'field_shorttext':
          $result = db_fetch_object(db_query("SELECT field_shorttext, format FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']));
          $additions = array($field['field_name'] => array('value' => $result->field_shorttext, 'format' => $result->format));
          break;
        case 'field_longtext':
          $result = db_fetch_object(db_query("SELECT field_longtext, format FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']));
          $additions = array($field['field_name'] => array('value' => $result->field_longtext, 'format' => $result->format));
          break;
        case 'field_integer':
          $result = db_fetch_object(db_query("SELECT field_int FROM {node_field_int_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']));
          $additions = array($field['field_name'] => $result->field_int);
          break;
        case 'field_decimal':
          $result = db_fetch_object(db_query("SELECT field_float FROM {node_field_float_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']));
          $additions = array($field['field_name'] => $result->field_float);
          break;
      }
      return $additions;

    case 'view':
      $output = '';
      $node_field = $node->$field['field_name'];
      switch($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          if ($field['text_processing']) {
            $output = check_markup($node_field['value'], $node_field['format'], isset($node->in_preview) ? $node->in_preview : FALSE);
          }
          else {
            $output = check_plain($node_field['value']);
          }
          break;
        case 'field_integer':
        case 'field_decimal':
          $output = $node_field;
          break;
      }
      return $output;

    case 'form':
      $form = array();
      $node_field = $node->$field['field_name'];

      switch($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          $form[$field['field_name']] = array('#tree' => TRUE);
          if ($field['rows'] == 1) {
            $form[$field['field_name']]['value'] = array(
              '#type' => 'textfield',
              '#title' => t($field['label']),
              '#default_value' => $node_field['value'],
              '#required' => $field['required'],
            );
          }
          else {
            $form[$field['field_name']]['value'] = array(
              '#type' => 'textarea',
              '#title' => t($field['label']),
              '#default_value' => $node_field['value'],
              '#required' => $field['required'],
              '#rows' => $field['rows'],
            );
          }
          if ($field['text_processing']) {
            $form[$field['field_name']] = array_merge($form[$field['field_name']], filter_form($node_field['format']));
          }
          break;
        case 'field_integer':
        case 'field_decimal':
          $form[$field['field_name']] = array(
            '#type' => 'textfield',
            '#title' => t($field['label']),
            '#default_value' => $node_field['value'],
            '#required' => $field['required'],
          );
          break;
      }
      return $form;

    case 'validate':
      $node_field = $node->$field['field_name'];

      switch($field['type']) {
        case 'field_shorttext':
        case 'field_longtext':
          break;
        case 'field_integer':
        case 'field_decimal':
          if (isset($node_field)) {
            if ($node_field != '') {
              if (is_numeric($field['min']) && $node_field < $field['min']) {
                form_set_error($field['field_name'] .'][value', t('The value of %name may be no smaller than %min.', array('%name' => t($field['label']), '%min' => $field['min'])));
              }
              if (is_numeric($field['max']) && $node_field > $field['max']) {
                form_set_error($field['field_name'] .'][value', t('The value of %name may be no larger than %max.', array('%name' => t($field['label']), '%max' => $field['max'])));
              }
            }
          }
          break;
      }
      return;

    case 'insert':
      $node_field = $node->$field['field_name'];
      switch($field['type']) {
        case 'field_shorttext':
          db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, field_shorttext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          break;
        case 'field_longtext':
          db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, field_longtext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          break;
        case 'field_integer':
          db_query("INSERT INTO {node_field_int_data} (vid, field_name, field_int) VALUES (%d, '%s', %d)", $node->vid, $field['field_name'], $node_field);
          break;
        case 'field_decimal':
          db_query("INSERT INTO {node_field_float_data} (vid, field_name, field_float) VALUES (%d, '%s', %d)", $node->vid, $field['field_name'], $node_field);
          break;
      }
      return;

    case 'update':
      $node_field = $node->$field['field_name'];
      // Delete and insert, rather than update, in case a field was added.
      switch($field['type']) {
        case 'field_shorttext':
          db_query("DELETE FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, field_shorttext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          break;
        case 'field_longtext':
          db_query("DELETE FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, field_longtext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          break;
        case 'field_integer':
          db_query("DELETE FROM {node_field_int_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          db_query("INSERT INTO {node_field_int_data} (vid, field_name, field_int) VALUES (%d, '%s', %d)", $node->vid, $field['field_name'], $node_field);
          break;
        case 'field_decimal':
          db_query("DELETE FROM {node_field_float_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          db_query("INSERT INTO {node_field_float_data} (vid, field_name, field_float) VALUES (%d, '%s', %d)", $node->vid, $field['field_name'], $node_field);
          break;
      }
      return;

    case 'delete':
      switch($field['type']) {
        case 'field_shorttext':
          db_query("DELETE FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
        case 'field_longtext':
          db_query("DELETE FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
        case 'field_integer':
          db_query("DELETE FROM {node_field_int_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
        case 'field_decimal':
          db_query("DELETE FROM {node_field_float_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
      }
      return;
  }
}

/**
 * Implementation of hook_field_query().
 */
function field_field_query($field, $op, $value) {
  $query_additions = array();

  switch ($field['type']) {
    case 'field_shorttext':
    case 'field_longtext':
      $table_name = ($field['type'] == 'field_shorttext' ? 'node_field_shorttext_data' : 'node_field_longtext_data');
      $column_name = ($field['type'] == 'field_shorttext' ? 'field_shorttext' : 'field_longtext');

      switch ($op) {
        case 'is':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." = '%s'";
          $query_additions['data'] = array($value);
          break;

        case 'contains':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." LIKE '%%%s%%'";
          $query_additions['data'] = array($value);
          break;

        case 'like':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." LIKE '%s'";
          $query_additions['data'] = array($value);
          break;
      }
      break;

    case 'field_integer':
    case 'field_decimal':
      $table_name = ($field['type'] == 'field_integer' ? 'node_field_int_data' : 'node_field_float_data');
      $column_name = ($field['type'] == 'field_integer' ? 'field_int' : 'field_float');

      switch ($op) {
        case 'is':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." = %d";
          $query_additions['data'] = array($value);
          break;

        case 'over':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." > %d";
          $query_additions['data'] = array($value);
          break;

        case 'under':
          $query_additions['tables'] = array('%table' => $table_name);
          $query_additions['where'] = "%table.". $column_name ." < %d";
          $query_additions['data'] = array($value);
          break;
      }
      break;
  }

  return $query_additions;
}

?>