<?php
// $Id$

/**
 * @file
 * Renders URL-specified listings of content.
 */

/**
 * Implementation of hook_help().
 */
function list_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Renders URL-specified listings of content.');
  }
}

/**
 * Implementation of hook_menu().
 */
function list_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'list', 'title' => t('list'),
      'callback' => 'list_page', 'access' => user_access('access content'),
      'type' => MENU_CALLBACK);
  }

  return $items;
}

/**
 * Menu callback; presents a listing of nodes.
 */
function list_page() {
  $output = '';

  $arguments = explode('/', $_GET['q']);
  array_shift($arguments);

  $conditions = array();
  $sort = array();

  while (count($arguments)) {
    $field = array_shift($arguments);
    $op = array_shift($arguments);
    $value = array_shift($arguments);

    $conditions[] = array('field' => $field, 'op' => $op, 'value' => $value);
  }

  $result = content_node_query($conditions, $sort);

  while ($node = db_fetch_object($result)) {
    $node = node_load($node->nid);
    $output .= node_view($node);
  }

  return $output;
}

?>