<?php
// $Id$

/**
 * @file
 * Defines standard simple field types.
 */

/**
 * Implementation of hook_help().
 */
function text_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Defines simple text field types. <em>Note: Requires content.module.</em>');
  }
}

/**
 * Implementation of hook_field_info().
 */
function text_field_info() {
  return array(
    'text_shorttext' => array('label' => 'Short Text'),
    'text_longtext' => array('label' => 'Long Text'),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function text_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $form = array();
      $options = array(0 => t('Plain text'), 1 => t('Filtered text (user selects input format)'));
      $form['text_processing'] = array(
        '#type' => 'radios',
        '#title' => t('Text processing'),
        '#default_value' => $field['text_processing'] ? $field['text_processing'] : 0,
        '#options' => $options,
      );
      return $form;

    case 'validate':
      break;

    case 'save':
      return array('text_processing');
      break;
  }
}

/**
 * Implementation of hook_field().
 */
function text_field($op, &$node, $field, $a2, $a3, $a4) {
  switch ($op) {
    case 'load':
      switch($field['type']) {
        case 'text_shorttext':
          $result = db_query("SELECT field_shorttext, format FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']);
          if ($field['multiple']) {
            $values = array();
            while ($value = db_fetch_object($result)) {
              $values[] = array('value' => $value->field_shorttext, 'format' => $value->format);
            }
            $additions = array($field['field_name'] => $values);
          }
          else {
            $value = db_fetch_object($result);
            $additions = array($field['field_name'] => array('value' => $value->field_shorttext, 'format' => $value->format));
          }
          break;
        case 'text_longtext':
          $result = db_query("SELECT field_longtext, format FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s' ORDER BY delta", $node->vid, $field['field_name']);
          if ($field['multiple']) {
            $values = array();
            while ($value = db_fetch_object($result)) {
              $values[] = array('value' => $value->field_longtext, 'format' => $value->format);
            }
            $additions = array($field['field_name'] => $values);
          }
          else {
            $value = db_fetch_object($result);
            $additions = array($field['field_name'] => array('value' => $value->field_longtext, 'format' => $value->format));
          }
          break;
      }
      return $additions;

    case 'view':
      $output = '';
      $node_field = $node->$field['field_name'];
      if ($field['multiple']) {
        foreach ($node_field as $delta => $item) {
          $node_field[$delta]['view'] = text_field_view($field, $item['value'], $item, $node);
        }
      }
      else {
        $node_field['view'] = text_field_view($field, $node_field['value'], $node_field, $node);
      }
      $node->$field['field_name'] = $node_field;
      if ($field['multiple']) {
        $output = '';
        foreach ($node_field as $delta => $item) {
          $output .= '<div class="'. $field['field_name'] .'">'. $item['view'] .'</div>';
        }
        return $output;
      }
      else {
        return '<div class="'. $field['field_name'] .'">'. $node_field['view'] .'</div>';
      }

    case 'insert':
      $node_field = $node->$field['field_name'];
      switch($field['type']) {
        case 'text_shorttext':
          if ($field['multiple']) {
            foreach ($node_field as $delta => $item) {
              db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, delta, field_shorttext, format) VALUES (%d, '%s', %d, '%s', %d)", $node->vid, $field['field_name'], $delta, $item['value'], $item['format']);
            }
          }
          else {
            db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, field_shorttext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          }
          break;
        case 'text_longtext':
          if ($field['multiple']) {
            foreach ($node_field as $delta => $item) {
              db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, delta, field_longtext, format) VALUES (%d, '%s', %d, '%s', %d)", $node->vid, $field['field_name'], $delta, $item['value'], $item['format']);
            }
          }
          else {
            db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, field_longtext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          }
          break;
      }
      return;

    case 'update':
      $node_field = $node->$field['field_name'];
      // Delete and insert, rather than update, in case a field was added.
      switch($field['type']) {
        case 'text_shorttext':
          db_query("DELETE FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          if ($field['multiple']) {
            foreach ($node_field as $delta => $item) {
              db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, delta, field_shorttext, format) VALUES (%d, '%s', %d, '%s', %d)", $node->vid, $field['field_name'], $delta, $item['value'], $item['format']);
            }
          }
          else {
            db_query("INSERT INTO {node_field_shorttext_data} (vid, field_name, field_shorttext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          }
          break;
        case 'text_longtext':
          db_query("DELETE FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          if ($field['multiple']) {
            foreach ($node_field as $delta => $item) {
              db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, delta, field_longtext, format) VALUES (%d, '%s', %d, '%s', %d)", $node->vid, $field['field_name'], $delta, $item['value'], $item['format']);
            }
          }
          else {
            db_query("INSERT INTO {node_field_longtext_data} (vid, field_name, field_longtext, format) VALUES (%d, '%s', '%s', %d)", $node->vid, $field['field_name'], $node_field['value'], $node_field['format']);
          }
          break;
      }
      return;

    case 'delete':
      switch($field['type']) {
        case 'field_shorttext':
          db_query("DELETE FROM {node_field_shorttext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
        case 'field_longtext':
          db_query("DELETE FROM {node_field_longtext_data} WHERE vid = %d AND field_name = '%s'", $node->vid, $field['field_name']);
          break;
      }
      return;
  }
}

/**
 * Implementation of hook_widget_info().
 */
function text_widget_info() {
  return array(
    'text' => array(
      'label' => 'Text Field',
      'field types' => array('text_shorttext', 'text_longtext'),
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function text_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':
      $form = array();
      $form['rows'] = array(
        '#type' => 'textfield',
        '#title' => t('Rows'),
        '#default_value' => $widget['rows'] ? $widget['rows'] : 1,
        '#required' => TRUE,
      );
      return $form;

    case 'validate':
      if (!is_numeric($widget['rows']) || intval($widget['rows']) != $widget['rows'] || $widget['rows'] <= 0) {
        form_set_error('rows', t('"Rows" must be a positive integer.'));
      }
      break;

    case 'save':
      return array('rows');
  }
}


/**
 * Implementation of hook_widget().
 */
function text_widget($op, &$node, $field) {
  switch ($op) {
    case 'form':
      $form = array();
      $node_field = $node->$field['field_name'];

      $form[$field['field_name']] = array('#tree' => TRUE);

      if ($field['multiple']) {
        foreach (range(0, 2) as $delta) {
          if ($field['widget']['rows'] == 1) {
            $form[$field['field_name']][$delta]['value'] = array(
              '#type' => 'textfield',
              '#title' => t($field['widget']['label']),
              '#default_value' => $node_field[$delta]['value'],
              '#required' => ($delta == 0) ? $field['required'] : FALSE,
            );
          }
          else {
            $form[$field['field_name']][$delta]['value'] = array(
              '#type' => 'textarea',
              '#title' => t($field['widget']['label']),
              '#default_value' => $node_field[$delta]['value'],
              '#required' => ($delta == 0) ? $field['required'] : FALSE,
              '#rows' => $field['widget']['rows'],
            );
          }
          if ($field['text_processing']) {
            $form[$field['field_name']][$delta]['format'] = filter_form($node_field[$delta]['format'], NULL, array($field['field_name'], $delta, 'format'));
          }
        }
      }
      else {
        if ($field['widget']['rows'] == 1) {
          $form[$field['field_name']]['value'] = array(
            '#type' => 'textfield',
            '#title' => t($field['widget']['label']),
            '#default_value' => $node_field['value'],
            '#required' => $field['required'],
          );
        }
        else {
          $form[$field['field_name']]['value'] = array(
            '#type' => 'textarea',
            '#title' => t($field['widget']['label']),
            '#default_value' => $node_field['value'],
            '#required' => $field['required'],
            '#rows' => $field['widget']['rows'],
          );
        }
        if ($field['text_processing']) {
          $form[$field['field_name']]['format'] = filter_form($node_field['format'], NULL, array($field['field_name'], 'format'));
        }
      }
      return $form;

    case 'validate':
      return;

    case 'submit':
      return;
  }
}

/**
 * Implementation of hook_field_view() which performs any translation necessary.
 */
function text_field_view($field, $value, $addlfields = array(), $node = NULL) {
  // check permissions in check_markup if previewing.
  $preview = ($node && isset($node->in_preview));

  if ($field['text_processing']) {
    return check_markup($value, $addlfields['format'], $preview);
  }
  else {
    return check_plain($value);
  }
}

/**
 * Implementation of hook_views_tables().
 */
function text_views_tables() {
  $tables = array();

  $fields = _content_fields();
  foreach ($fields as $field) {
    if ($field['type'] == 'text_shorttext') {
      $tables['node_field_shorttext_data_'. $field['field_name']] = array(
        'name' => 'node_field_shorttext_data',
        'join' => array(
          'left' => array(
            'table' => 'node',
            'field' => 'vid',
          ),
          'right' => array(
            'field' => 'vid',
            'extra' => array('field_name' => $field['field_name']),
          ),
        ),
        'fields' => array(
          'field_shorttext' => array(
            'name' => 'Short Text: '. $field['field_name'],
            'sortable' => TRUE,
          ),
        ),
        'sorts' => array(
          'field_shorttext' => array('name' => 'Short Text: '. $field['field_name']),
        ),
        'filters' => array(
          'field_shorttext' => array(
            'name' => 'Short Text: '. $field['field_name'],
            'operator' => array(
              '='  => 'is',
              'contains' => 'contains',
              'begins' => 'begins with',
              'ends' => 'ends wth',
              'LIKE'  => 'matches pattern',
            ),
            'operator-handler' => '_text_filter_operator',
          ),
        ),
      );
    }
  }

  return $tables;
}

/**
 * Format the WHERE portion of a query.
 */
function _text_filter_operator($field, $operator, $value) {
  switch ($operator) {
    case 'contains':
      $string = $field ." LIKE '%%%s%%'";
      break;
    case 'begins':
      $string = $field ." LIKE '%s%%'";
      break;
    case 'ends':
      $string = $field ." LIKE '%%%s'";
      break;
    default:
      $string = $field ." $operator '%s'";
  }
  return array($string, $value);
}

