<?php
// $Id$

/**
 * @file
 * Defines a field type for referencing a user from a node.
 */

/**
 * Implementation of hook_field_info().
 *
 * Here we indicate that the content module will use its default
 * handling for the view of this field.
 */
function userreference_field_info() {
  return array(
    'userreference' => array(
      'label' => 'User Reference',
      'callbacks' => array(
        'view' => CONTENT_CALLBACK_DEFAULT,
        'tables' => CONTENT_CALLBACK_DEFAULT,
        'arguments' => CONTENT_CALLBACK_DEFAULT,
        ),
      ),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function userreference_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $form = array();
      $form['referenceable_roles'] = array(
        '#type' => 'checkboxes',
        '#title' => t('User roles that can be referenced'),
        '#default_value' => isset($field['referenceable_roles']) ? $field['referenceable_roles'] : array(),
        '#options' => user_roles(1),
      );
      return $form;

    case 'save':
      return array('referenceable_roles');

    case 'database columns':
      $columns = array(
        'uid' => array('type' => 'int', 'unsigned' => TRUE,  'not null' => FALSE),
      );
      return $columns;

    case 'filters':
      return array(
        'default' => array(
          'list' => '_userreference_filter_handler',
          'list-type' => 'list',
          'operator' => 'views_handler_operator_or',
          'value-type' => 'array',
          'extra' => array('field' => $field),
        ),
      );
  }
}

/**
 * Implementation of hook_field().
 */
function userreference_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    case 'validate':
      foreach ($items as $delta => $item) {
        if (is_array($item) && !empty($item['error_field'])) {
          $error_field = $item['error_field'];
          unset($item['error_field']);
          if (!empty($item['uid']) && !in_array($item['uid'], array_keys(_userreference_potential_references($field)))) {
            form_set_error($error_field, t('%name : Invalid user.', array('%name' => t($field['widget']['label']))));
          }
        }
      }
      return;

    // Don't save empty items.
    case 'presave':
      if (is_array($items)) {
        foreach ($items as $delta => $item) {
          if ($delta > 0 && empty($item)) {
            unset($items[$delta]);
            unset($node->{$field['field_name'][$delta]});
          }
        }
      }
      break;
  }
}

/**
 * Implementation of hook_field_formatter_info().
 */
function userreference_field_formatter_info() {
  return array(
    'default' => array(
      'label' => 'Default',
      'field types' => array('userreference'),
    ),
    'plain' => array(
      'label' => 'Plain text',
      'field types' => array('userreference'),
    ),
  );
}

/**
 * Implementation of hook_field_formatter().
 */
function userreference_field_formatter($field, $item, $formatter, $node) {
  $text = '';
  if (isset($item['uid'])) {
    $referenced_user = user_load(array('uid' => $item['uid']));
    if ($referenced_user) {
      $text = theme('username', $referenced_user);
    }
  }

  switch ($formatter) {
    case 'plain':
      return strip_tags($text);

    default:
      return $text;
  }
}

/**
 * Implementation of hook_widget_info().
 *
 * We need custom handling of multiple values for userreference_select
 * because we need to combine them into a options list rather than
 * display multiple elements.
 *
 * We will use the content module's default handling for default value.
 *
 * Callbacks can be omitted if default handing is used.
 * They're included here just so this module can be used
 * as an example for custom modules that might do things
 * differently.
 */
function userreference_widget_info() {
  return array(
    'userreference_select' => array(
      'label' => 'Select List',
      'field types' => array('userreference'),
      'multiple values' => CONTENT_HANDLE_MODULE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
        ),
    ),
    'userreference_autocomplete' => array(
      'label' => 'Autocomplete Text Field',
      'field types' => array('userreference'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
        ),
    ),
  );
}

/**
 * Implementation of hook_widget().
 *
 * Attach a single form element to the form. It will be built out and
 * validated in the callback(s) listed in hook_elements. We build it
 * out in the callbacks rather than here in hook_widget so it can be
 * plugged into any module that can provide it with valid
 * $field information.
 *
 * Content module will set the weight, field name and delta values
 * for each form element. This is a change from earlier CCK versions
 * where the widget managed its own multiple values.
 *
 * If there are multiple values for this field, the content module will
 * call this function as many times as needed.
 *
 * @param $form
 *   the entire form array, $form['#node'] holds node information
 * @param $form_state
 *   the form_state, $form_state['values'][$field['field_name']]
 *   holds the field's form values.
 * @param $field
 *   the field array
 * @param $items
 *   array of default values for this field
 * @param $delta
 *   the order of this item in the array of subelements (0, 1, 2, etc)
 *
 * @return
 *   the form item for a single element for this field
 */
function userreference_widget(&$form, &$form_state, $field, $items, $delta = 0) {

  // No hard-coding of column names so this can be used by any field.
  // This is a change from earlier versions which hard-coded 'uid'.
  $db_info = content_database_info($field);
  $columns = array_keys($db_info['columns']);

  switch ($field['widget']['type']) {
    case 'userreference_select':
      // The userreference_select widget doesn't need to create its own
      // element, it can use the optionwidgets_select element.
      $element = array(
        '#type' => 'optionwidgets_select',
        '#field' => $field,
        '#columns' => $columns,
        '#delta' => $delta,
        '#weight' => t($field['widget']['weight']),
        '#default_value' => $items,
      );
      break;

    case 'userreference_autocomplete':
      // The userreference autocomplete widget doesn't need to create its own
      // element, it can use the text_textfield element and add an autocomplete
      // path and some extra processing to it.
      $element = array(
        '#type' => 'text_textfield',
        '#field' => $field,
        '#columns' => $columns,
        '#delta' => $delta,
        '#weight' => t($field['widget']['weight']),
        '#default_value' => isset($items[$delta]) ? $items[$delta] : NULL,
        '#value_callback' => 'userreference_autocomplete_value',
        '#autocomplete_path' => 'user/autocomplete',
        '#element_validate' => array('userreference_autocomplete_validate'),
      );
      break;
  }
  return $element;
}

/**
 * Value for a userreference autocomplete element.
 *
 * Substitute in the user name for the user uid.
 */
function userreference_autocomplete_value($element, $edit = FALSE) {
  if (func_num_args() == 1) {
    $field_key  = $element['#columns'][0];
    if (!empty($element['#default_value'][$field_key])) {
      $value = db_result(db_query("SELECT name FROM {users} WHERE uid = '%d'", $element['#default_value'][$field_key]));
      return array($field_key => $value);
    }
  }
}

function userreference_autocomplete_validate($element, &$form_state) {
  $field = $element['#field'];
  $field_key  = $element['#columns'][0];
  $value = $element['#value'][$field_key];
  if (!empty($value)) {
    $value = db_result(db_query("SELECT uid FROM {users} WHERE name = '%s'", $value));
  }
  if (!empty($value)) {
    form_set_value($element[$field_key], $value, $form_state);
  }
  elseif ($element['#delta'] > 0) {
    // Don't save empty fields when they're not the first value (keep '0' otherwise)
    form_set_value($element[$field_key], 0, $form_state);
  }
}

/**
 * Implementation of hook_allowed_values().
 */
function userreference_allowed_values($field) {
  $options = _userreference_potential_references($field);
  if (!$field['required']) {
    $options = array('none' => t('<none>')) + $options;
  }
  return $options;
}

/**
 * Fetch an array of all candidate referenced users, for use in presenting the selection form to the user.
 */
function _userreference_potential_references($field) {
  $roles = array();
  if (isset($field['referenceable_roles']) && is_array($field['referenceable_roles'])) {
    // keep only selected checkboxes
    $roles = array_filter($field['referenceable_roles']);
    // filter invalid values that seems to get through sometimes ??
    $roles = array_intersect(array_keys(user_roles(1)), $roles);
  }
  if (empty($roles) || in_array(DRUPAL_AUTHENTICATED_RID, $roles)) {
    $result = db_query('SELECT u.name, u.uid FROM {users} u WHERE uid > 0 ORDER BY u.name ASC');
  }
  else {
    $result = db_query('SELECT u.name, u.uid FROM {users} u LEFT JOIN {users_roles} r ON u.uid = r.uid WHERE u.uid > 0 AND r.rid IN ('. implode($roles, ',') .') ORDER BY u.name ASC');
  }

  $users = array();
  while ($user = db_fetch_object($result)) {
    $users[$user->uid] = $user->name;
  }
  return $users;
}

/**
 * Provide a list of users to filter on.
 */
function _userreference_filter_handler($op, $filterinfo) {
  $options = views_handler_filter_usercurrent();
  $options = $options + _userreference_potential_references($filterinfo['extra']['field']);
  return $options;
}